version: '2'

services:
  # mongodb-api:
  #   image: 'bitnami/mongodb:3.6'
  #   labels:
  #     kompose.service.type: nodeport
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - 'mongodb_data:/bitnami'
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=worsie
      - MYSQL_USER=worsie
      - MYSQL_PASSWORD=worsie
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: test 
    ports:
      - "8080:80"

volumes:
  mongodb_data:
    driver: local